/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Participa;

import Conexion.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author moises
 */
public class ModificarParticipacion extends javax.swing.JFrame {
    Participacion par1=new Participacion();
      Participacion par2=new Participacion();
        Pago pa1=new Pago();
        int idPersona;
        String nombre;
        String nombreCompleto;
        String aPaterno;
        String aMaterno;
        String nombreCurso;
        String horario;
        String[] claves;
        String clave;
        String tipoActividad;
        String estado1;
        String act;
        String claveC;
        int idActividad;
        String idConf;
        
    /**
     * Creates new form ModificarParticipacion
     */
    public ModificarParticipacion() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    public ModificarParticipacion(String noConfirmacion, String Participante,String Actividad,String tema,String estado) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        idConf=noConfirmacion;
        llenarCampos( noConfirmacion,  Participante,Actividad, tema);
        estado1=estado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        temas = new javax.swing.JComboBox();
        participantes = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cursos = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();

        jLabel6.setText("Nombre Participante");

        jLabel7.setText("Nombre de la actividad");

        jLabel8.setText("Horario de la actividad");

        jLabel5.setText("Pagado/Pendiente");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField5.setText("jTextField5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("Actividad:");

        jLabel1.setText("Participante:");

        temas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                temasItemStateChanged(evt);
            }
        });
        temas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temasActionPerformed(evt);
            }
        });

        participantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantesActionPerformed(evt);
            }
        });

        jLabel10.setText("###");

        jLabel9.setText("No Confirmación:");

        jButton2.setText("Guardar ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cursos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Curso", "Taller", "Platica", "Conferencia", "Foro" }));
        cursos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cursosItemStateChanged(evt);
            }
        });
        cursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursosActionPerformed(evt);
            }
        });

        jLabel11.setText("Tema:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temas, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel10)
                    .addComponent(participantes, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cursos, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addComponent(participantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(68, 68, 68)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void temasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_temasItemStateChanged

    }//GEN-LAST:event_temasItemStateChanged

    private void temasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temasActionPerformed
        try {
            int i = temas.getSelectedIndex();
            String clave="";
            if( i >= 0)
            clave= claves[i];
            Connection cn = null;
            Statement s;
            String con3 = "SELECT * From  Actividad WHERE Clave='"+clave+"' ;";
            Conexion cx = new Conexion();
            cn = cx.Enlace(cn);
            s = cn.createStatement();
            ResultSet rs = s.executeQuery(con3);
            rs = s.executeQuery(con3);
            if(rs.next()){
                idActividad =(int)rs.getObject("idActividad");
                claveC=(String)rs.getObject("clave");
                
            }
            s.close();
            cn.close();
        } catch (SQLException ex) {
            Logger.getLogger(RegistraParticipacion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_temasActionPerformed

    private void participantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantesActionPerformed

    }//GEN-LAST:event_participantesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String temaCombo=temas.getSelectedItem().toString();
        String id;
        String tema = temaCombo.substring(0, temaCombo.indexOf(" "));
        int noConf= Integer.valueOf(idConf);
        
        try {
            Connection cn = null;
            Statement s;
            Conexion cx = new Conexion();
            String p=participantes.getSelectedItem().toString();
            String idp="";
            idp= p.substring(0, p.indexOf(" "));
            int noC= Integer.valueOf(jLabel10.getText());
            String e;
            if(estado1.equals("pendiente")){
                estado1="0";
            }else{
                estado1="1";
            }
            String con = "UPDATE Participa SET idParticipante="+idp+",idActividad="+idActividad+",estadoPago="+estado1+" WHERE idConfirmacion= "+noConf+" ;";
            cn = cx.Enlace(cn);
            s = cn.createStatement();
            s.executeUpdate(con);
            s.close();
            cn.close();
            JOptionPane.showMessageDialog(this, "Registro completo");
            dispose();
        } catch (SQLException ex) {
            System.out.println("Error de registro de curso - "+ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cursosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cursosItemStateChanged
        act=cursos.getSelectedItem().toString();
    }//GEN-LAST:event_cursosItemStateChanged

    private void cursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursosActionPerformed
        temas.removeAllItems();

        int cont=0;
        try {
            Connection cn = null;
            Statement s;
            act=cursos.getSelectedItem().toString();
            String con3 = "SELECT * From "+act+" ;";
            Conexion cx = new Conexion();
            cn = cx.Enlace(cn);
            s = cn.createStatement();
            ResultSet rs = s.executeQuery(con3);
            rs = s.executeQuery(con3);
            claves= new String[100];
            while(rs.next()){
                nombreCurso= (String) rs.getObject("Tema");
                horario=(String)rs.getObject("horario");
                claves[cont]=(String) rs.getObject("Clave");
                for (int i = 0; i <1 ; i++) {
                    temas.addItem(nombreCurso+" "+horario);
                }
                cont++;
            }
            s.close();
            cn.close();
        } catch (SQLException ex) {
            Logger.getLogger(RegistraParticipacion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cursosActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
    public void llenarCampos(String noConfirmacion, String Participante,String Actividad, String tema){
        int b=0;
        int id=-1;
        act=cursos.getSelectedItem().toString();
        Connection cn = null;
        Statement s;
        try {
            Conexion cx = new Conexion();
            cn = cx.Enlace(cn);
            s = cn.createStatement();
            ResultSet rs;
                jLabel10.setText(noConfirmacion);
                String con2 = "SELECT id, nombre, aPaterno,aMaterno From Persona;";
                rs = s.executeQuery(con2);
                while(rs.next()){
                    idPersona= (int) rs.getObject("id");
                    String idP=String.valueOf(idPersona);
                    nombre=(String) rs.getObject("nombre");
                    aPaterno=(String) rs.getObject("aPaterno");
                    aMaterno=(String) rs.getObject("aMaterno");
                    nombreCompleto=idPersona+" "+nombre+" "+aPaterno+" "+aMaterno;
                    for (int i = 0; i <1 ; i++) {
                        participantes.addItem(nombreCompleto);
                    }
                    
                }
                participantes.setSelectedItem(Participante);
                cursos.setSelectedItem(Actividad);
                temas.setSelectedItem(tema);
                s.close();
                cn.close();

            //}
        } catch (SQLException ex) {
              Logger.getLogger(RegistraParticipacion.class.getName()).log(Level.SEVERE, null, ex);
          
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarParticipacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarParticipacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarParticipacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarParticipacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarParticipacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cursos;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JComboBox participantes;
    private javax.swing.JComboBox temas;
    // End of variables declaration//GEN-END:variables
}
