/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Participa;
import Conexion.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author moises
 */
public class RegistraParticipacion extends javax.swing.JFrame {
      Participacion par1=new Participacion();
      Participacion par2=new Participacion();
        Pago pa1=new Pago();
        int idPersona;
        String nombre;
        String nombreCompleto;
        String aPaterno;
        String aMaterno;
        String nombreCurso;
        String horario;
        String[] claves;
        String clave;
        String tipoActividad;
        int estado;
        String act;
        String claveC;
        int idActividad;
     public void ConsultaParticipante(){
        int b=0;
        int id=-1;
        act=cursos.getSelectedItem().toString();
        Connection cn = null;
        Statement s;
        try {
            Conexion cx = new Conexion();
            String con = "SELECT * From Participa ;";
            cn = cx.Enlace(cn);
            s = cn.createStatement();
            ResultSet rs = s.executeQuery(con);
            //while(b==0){
                while(rs.next()){
                    par1.setIdConfirmacion((int) rs.getObject("idConfirmacion"));
                    par1.setIdActividad((int) rs.getObject("idActividad"));
                    par1.setIdParticipante((int) rs.getObject("idParticipante"));
                    par1.setEstadoPago((int) rs.getObject("estadoPago"));
                    if(id<par1.getIdConfirmacion())
                        id=par1.getIdConfirmacion();
                }                
                id=id+1;
                jLabel10.setText(String.valueOf(id));
                String con2 = "SELECT id, nombre, aPaterno,aMaterno From Persona;";
                rs = s.executeQuery(con2);
                while(rs.next()){
                    idPersona= (int) rs.getObject("id");
                    String idP=String.valueOf(idPersona);
                    nombre=(String) rs.getObject("nombre");
                    aPaterno=(String) rs.getObject("aPaterno");
                    aMaterno=(String) rs.getObject("aMaterno");
                    nombreCompleto=idPersona+" "+nombre+" "+aPaterno+" "+aMaterno;
                    for (int i = 0; i <1 ; i++) {
                        participantes.addItem(nombreCompleto);
                    }
                    
                }
                
                
                s.close();
              cn.close();

            //}
        } catch (SQLException ex) {
              Logger.getLogger(RegistraParticipacion.class.getName()).log(Level.SEVERE, null, ex);
          }
        }
    public RegistraParticipacion() {
        initComponents();
        ConsultaParticipante();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        participantes = new javax.swing.JComboBox();
        cursos = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        temas = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Participante:");

        jLabel2.setText("Actividad:");

        jButton2.setText("Guardar ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("No Confirmación:");

        jLabel10.setText("###");

        participantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantesActionPerformed(evt);
            }
        });

        cursos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Curso", "Taller", "Platica", "Conferencia", "Foro" }));
        cursos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cursosItemStateChanged(evt);
            }
        });
        cursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursosActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        temas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                temasItemStateChanged(evt);
            }
        });
        temas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temasActionPerformed(evt);
            }
        });

        jLabel6.setText("Tema:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temas, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel10)
                    .addComponent(participantes, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cursos, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addComponent(participantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(68, 68, 68)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String temaCombo=temas.getSelectedItem().toString();
        String id;
        String tema = temaCombo.substring(0, temaCombo.indexOf(" "));
        try {
              Connection cn = null;
              Statement s;
              Conexion cx = new Conexion();
              String p=participantes.getSelectedItem().toString();
              String idp="";
              idp= p.substring(0, p.indexOf(" "));
              int noC= Integer.valueOf(jLabel10.getText());
              String con = "INSERT INTO Participa (idParticipante,idActividad,estadoPago ) VALUES ("+idp+","+idActividad+","+0+");";
              cn = cx.Enlace(cn);
              s = cn.createStatement();
              s.executeUpdate(con);
              s.close();
              cn.close();
              JOptionPane.showMessageDialog(this, "Registro completo");
          } catch (SQLException ex) {
              System.out.println("Error de registro de curso - "+ex.getMessage());
          }
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void participantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantesActionPerformed
        
    }//GEN-LAST:event_participantesActionPerformed

    private void temasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_temasItemStateChanged
        

    }//GEN-LAST:event_temasItemStateChanged

    private void cursosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cursosItemStateChanged
        act=cursos.getSelectedItem().toString();
    }//GEN-LAST:event_cursosItemStateChanged

    private void cursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursosActionPerformed
        temas.removeAllItems();  
        int cont=0;
        try {
              Connection cn = null;
              Statement s;
              act=cursos.getSelectedItem().toString();
              String con3 = "SELECT * From "+act+" ;";
              Conexion cx = new Conexion();
              cn = cx.Enlace(cn);
              s = cn.createStatement();
              ResultSet rs = s.executeQuery(con3);
              rs = s.executeQuery(con3);
              claves= new String[100];
              while(rs.next()){
                  nombreCurso= (String) rs.getObject("Tema");
                  horario=(String)rs.getObject("horario");
                  claves[cont]=(String) rs.getObject("Clave");
                  for (int i = 0; i <1 ; i++) {
                      temas.addItem(nombreCurso+" "+horario);
                  }
                  cont++;
              }
          s.close();
              cn.close();
          } catch (SQLException ex) {
              Logger.getLogger(RegistraParticipacion.class.getName()).log(Level.SEVERE, null, ex);
          }
        
    }//GEN-LAST:event_cursosActionPerformed

    private void temasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temasActionPerformed
          try {
              int i = temas.getSelectedIndex();
              String clave="";
              if( i >= 0)
                  clave= claves[i];
              Connection cn = null;
              Statement s;
              String con3 = "SELECT * From  Actividad WHERE Clave='"+clave+"' ;";
              Conexion cx = new Conexion();
              cn = cx.Enlace(cn);
              s = cn.createStatement();
              ResultSet rs = s.executeQuery(con3);
              rs = s.executeQuery(con3);
              if(rs.next()){
                  idActividad =(int)rs.getObject("idActividad");
                  claveC=(String)rs.getObject("clave");
              }
              s.close();
              cn.close();
          } catch (SQLException ex) {
              Logger.getLogger(RegistraParticipacion.class.getName()).log(Level.SEVERE, null, ex);
          }
        
    }//GEN-LAST:event_temasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistraParticipacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistraParticipacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistraParticipacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistraParticipacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistraParticipacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cursos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox participantes;
    private javax.swing.JComboBox temas;
    // End of variables declaration//GEN-END:variables
}
